require "npcastro.options"
require "npcastro.keymaps"
require "npcastro.plugins"
require "npcastro.colorscheme"
require "npcastro.cmp"
require "npcastro.lsp"
require "npcastro.telescope"
require "npcastro.treesitter"
